version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4000:4000"
    environment:
      PRISMA_CONFIG: |
        port: 4000
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: 35.238.128.54
            user: team6_user
            password: starcraft is life
            rawAccess: true
            port: '3306'
            migrations: true